import pandas as pd

df = pd.read_excel("exercicio01.xlsx")
#print("Todos os dados")
#print(df.to_string())
#print("Exibir as 5 primeiras linhas\n")
#print(df.head())
#print("Exibir as 10 ultimas linhas\n")
#print(df.tail(10))
#print("Mostrar os nomes das colunas:\n")
#print(df.columns)
#print("Quantidade total de registros:\n")
#print(len(df))
#print("Valor máximo:\n")
#print(df["valor"].max())
#print("Valor mínimo:\n")
#print(df["valor"].min())
#print("Somar a quantidade:\n")
#print(df["quantidade"].sum())
#print("Média dps valores:\n")
#print(df["valor"].mean())
print("Listar produtos únicos:\n")
print(df["produto"].unique())
print("Listar produtos diferentes:\n")
print(df["produto"].nunique())